// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ElectricCurrent.generated.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace Sundew.Quantities
{
    using global::Sundew.Quantities.Engine;
    using global::Sundew.Quantities.Engine.Quantities;
    using global::Sundew.Quantities.Engine.Representations.Hierarchical.Units;
    using global::Sundew.Quantities.Engine.UnitSelection;
    using global::Sundew.Quantities.UnitSelection;
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Globalization;

    [GeneratedCode("Sundew.Quantities.Generator", "1.0.0.0")]
    public partial struct ElectricCurrent : IQuantity<ElectricCurrent, ElectricCurrentUnitSelector>
    {
        private readonly double value;

        public ElectricCurrent(double value, SelectUnit<ElectricCurrentUnitSelector> unitSelector)
            : this(value,  UnitBuilder.BuildUnit(unitSelector(new ElectricCurrentUnitSelector())))
        {
        }

        public ElectricCurrent(IQuantity quantity)
            : this(quantity.Value, quantity.Unit)
        {
        }

        public ElectricCurrent(double value)
            : this(value, units => units.BaseUnit)
        {
        }

        public ElectricCurrent(double value, IUnit unit)
        {
            this.value = value;
            this.Unit = unit;
        }

        double IQuantity.Value => this.value;

        public IUnit Unit { get; }

        public static ElectricCurrent operator +(ElectricCurrent quantity)
        {
            return quantity;
        }

        public static ElectricCurrent operator -(ElectricCurrent quantity)
        {
            return new ElectricCurrent(-quantity.value, quantity.Unit);
        }

        public static ElectricCurrent operator ++(ElectricCurrent quantity)
        {
            return new ElectricCurrent(quantity.value + 1, quantity.Unit);
        }

        public static ElectricCurrent operator --(ElectricCurrent quantity)
        {
            return new ElectricCurrent(quantity.value - 1, quantity.Unit);
        }

        public static ElectricCurrent operator +(ElectricCurrent lhs, double rhs)
        {
            return new ElectricCurrent(lhs.value + rhs, lhs.Unit);
        }

        public static ElectricCurrent operator -(ElectricCurrent lhs, double rhs)
        {
            return new ElectricCurrent(lhs.value - rhs, lhs.Unit);
        }

        public static ElectricCurrent operator *(ElectricCurrent lhs, double rhs)
        {
            return new ElectricCurrent(lhs.value * rhs, lhs.Unit);
        }

        public static ElectricCurrent operator /(ElectricCurrent lhs, double rhs)
        {
            return new ElectricCurrent(lhs.value / rhs, lhs.Unit);
        }

        public static ElectricCurrent operator +(ElectricCurrent lhs, ElectricCurrent rhs)
        {
            return new ElectricCurrent(QuantityOperations.Add(lhs, rhs));
        }

        public static ElectricCurrent operator -(ElectricCurrent lhs, ElectricCurrent rhs)
        {
            return new ElectricCurrent(QuantityOperations.Subtract(lhs, rhs));
        }

        public static double operator /(ElectricCurrent lhs, ElectricCurrent rhs)
        {
            return QuantityOperations.Divide(lhs, rhs).Value;
        }

        public static bool operator ==(ElectricCurrent lhs, ElectricCurrent rhs)
        {
            return QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator !=(ElectricCurrent lhs, ElectricCurrent rhs)
        {
            return !QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator >=(ElectricCurrent lhs, ElectricCurrent rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) >= 0;
        }

        public static bool operator <=(ElectricCurrent lhs, ElectricCurrent rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) <= 0;
        }

        public static bool operator >(ElectricCurrent lhs, ElectricCurrent rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) > 0;
        }

        public static bool operator <(ElectricCurrent lhs, ElectricCurrent rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) < 0;
        }

        public static Interval<ElectricCurrent> Interval(double min, double max, SelectUnit<ElectricCurrentUnitSelector> unitSelector)
        {
            return new Interval<ElectricCurrent>(min, max, unitSelector(new ElectricCurrentUnitSelector()));
        }

        public Squared<ElectricCurrent> Squared()
        {
            return new Squared<ElectricCurrent>(this);
        }

        public Cubed<ElectricCurrent> Cubed()
        {
            return new Cubed<ElectricCurrent>(this);
        }

        public double ToDouble(IUnit unit)
        {
            return QuantityOperations.ConvertToUnit(this, unit);
        }

        public IQuantity ToQuantity(IUnit unit)
        {
            return this.ToUnit(unit);
        }

        public ElectricCurrent ToUnit(IUnit unit)
        {
            return new ElectricCurrent(this.ToDouble(unit), unit);
        }

        public ElectricCurrent ToUnit(SelectUnit<ElectricCurrentUnitSelector> unitSelector)
        {
            return this.ToUnit(UnitBuilder.BuildUnit(unitSelector(new ElectricCurrentUnitSelector())));
        }

        public double ToDouble(SelectUnit<ElectricCurrentUnitSelector> unitSelector)
        {
            return this.ToDouble(UnitBuilder.BuildUnit(unitSelector(new ElectricCurrentUnitSelector())));
        }

        public override int GetHashCode()
        {
            return QuantityHelper.GetHashCode(this);
        }

        public override bool Equals(object obj)
        {
            return QuantityHelper.AreEqual(this, obj);
        }

        public bool Equals(IQuantity quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public bool Equals(ElectricCurrent quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public int CompareTo(object obj)
        {
            return QuantityHelper.CompareTo<ElectricCurrent>(this, obj);
        }

        public int CompareTo(IQuantity quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public int CompareTo(ElectricCurrent quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public override string ToString()
        {
            return this.ToString(CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat)
        {
            return this.ToString(unitFormat, null, CultureInfo.CurrentCulture);
        }

        public string ToString(string format)
        {
            return this.ToString(format, CultureInfo.CurrentCulture);
        }

        public string ToString(IFormatProvider formatProvider)
        {
            return this.ToString(null, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format)
        {
            return this.ToString(unitFormat, format, CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat, IFormatProvider formatProvider)
        {
            return this.ToString(unitFormat, null, formatProvider);
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return this.ToString(UnitFormat.Default, format, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format, IFormatProvider formatProvider)
        {
            return QuantityHelper.ToString(
                this.Unit.FormatValue(this.value, format, formatProvider),
                UnitHelper.GetNotation(this.Unit, unitFormat));
        }

        public ElectricCurrent CreateQuantity(double value, IUnit unit)
        {
            return new ElectricCurrent(value, unit);
        }

        IQuantity IDeferredQuantity.GetResult()
        {
            return this;
        }

        ElectricCurrentUnitSelector IQuantity<ElectricCurrent, ElectricCurrentUnitSelector>.CreateUnitSelector()
        {
            return new ElectricCurrentUnitSelector();
        }
    }
}