// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Inductance.generated.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace Sundew.Quantities
{
    using global::Sundew.Quantities.Core;
    using global::Sundew.Quantities.Representations.Expressions;
    using global::Sundew.Quantities.UnitSelection;
    using global::Sundew.Quantities.UnitSelectors;
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Globalization;

    [GeneratedCode("Sundew.Quantities.Generator", "1.0.0.0")]
    public partial struct Inductance : IQuantity<Inductance, InductanceUnitSelector>
    {
        private readonly double value;

        public Inductance(double value, SelectUnit<InductanceUnitSelector> unitSelector)
            : this(value,  UnitBuilder.BuildUnit(unitSelector(new InductanceUnitSelector())))
        {
        }

        public Inductance(IQuantity quantity)
            : this(quantity.Value, quantity.Unit)
        {
        }

        public Inductance(double value)
            : this(value, units => units.BaseUnit)
        {
        }

        public Inductance(double value, IUnit unit)
        {
            this.value = value;
            this.Unit = unit;
        }

        double IQuantity.Value => this.value;

        public IUnit Unit { get; }

        public static Inductance operator +(Inductance quantity)
        {
            return quantity;
        }

        public static Inductance operator -(Inductance quantity)
        {
            return new Inductance(-quantity.value, quantity.Unit);
        }

        public static Inductance operator ++(Inductance quantity)
        {
            return new Inductance(quantity.value + 1, quantity.Unit);
        }

        public static Inductance operator --(Inductance quantity)
        {
            return new Inductance(quantity.value - 1, quantity.Unit);
        }

        public static Inductance operator +(Inductance lhs, double rhs)
        {
            return new Inductance(lhs.value + rhs, lhs.Unit);
        }

        public static Inductance operator -(Inductance lhs, double rhs)
        {
            return new Inductance(lhs.value - rhs, lhs.Unit);
        }

        public static Inductance operator *(Inductance lhs, double rhs)
        {
            return new Inductance(lhs.value * rhs, lhs.Unit);
        }

        public static Inductance operator /(Inductance lhs, double rhs)
        {
            return new Inductance(lhs.value / rhs, lhs.Unit);
        }

        public static Inductance operator +(Inductance lhs, Inductance rhs)
        {
            return new Inductance(QuantityOperations.Add(lhs, rhs));
        }

        public static Inductance operator -(Inductance lhs, Inductance rhs)
        {
            return new Inductance(QuantityOperations.Subtract(lhs, rhs));
        }

        public static double operator /(Inductance lhs, Inductance rhs)
        {
            return QuantityOperations.Divide(lhs, rhs).Value;
        }

        public static bool operator ==(Inductance lhs, Inductance rhs)
        {
            return QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator !=(Inductance lhs, Inductance rhs)
        {
            return !QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator >=(Inductance lhs, Inductance rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) >= 0;
        }

        public static bool operator <=(Inductance lhs, Inductance rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) <= 0;
        }

        public static bool operator >(Inductance lhs, Inductance rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) > 0;
        }

        public static bool operator <(Inductance lhs, Inductance rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) < 0;
        }

        public static Interval<Inductance> Interval(double min, double max, SelectUnit<InductanceUnitSelector> unitSelector)
        {
            return new Interval<Inductance>(min, max, unitSelector(new InductanceUnitSelector()));
        }

        public Squared<Inductance> Squared()
        {
            return new Squared<Inductance>(this);
        }

        public Cubed<Inductance> Cubed()
        {
            return new Cubed<Inductance>(this);
        }

        public double ToDouble(IUnit unit)
        {
            return QuantityOperations.ConvertToUnit(this, unit);
        }

        public IQuantity ToQuantity(IUnit unit)
        {
            return this.ToUnit(unit);
        }

        public Inductance ToUnit(IUnit unit)
        {
            return new Inductance(this.ToDouble(unit), unit);
        }

        public Inductance ToUnit(SelectUnit<InductanceUnitSelector> unitSelector)
        {
            return this.ToUnit(UnitBuilder.BuildUnit(unitSelector(new InductanceUnitSelector())));
        }

        public double ToDouble(SelectUnit<InductanceUnitSelector> unitSelector)
        {
            return this.ToDouble(UnitBuilder.BuildUnit(unitSelector(new InductanceUnitSelector())));
        }

        public override int GetHashCode()
        {
            return QuantityHelper.GetHashCode(this);
        }

        public override bool Equals(object obj)
        {
            return QuantityHelper.AreEqual(this, obj);
        }

        public bool Equals(IQuantity quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public bool Equals(Inductance quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public int CompareTo(object obj)
        {
            return QuantityHelper.CompareTo<Inductance>(this, obj);
        }

        public int CompareTo(IQuantity quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public int CompareTo(Inductance quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public override string ToString()
        {
            return this.ToString(CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat)
        {
            return this.ToString(unitFormat, null, CultureInfo.CurrentCulture);
        }

        public string ToString(string format)
        {
            return this.ToString(format, CultureInfo.CurrentCulture);
        }

        public string ToString(IFormatProvider formatProvider)
        {
            return this.ToString(null, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format)
        {
            return this.ToString(unitFormat, format, CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat, IFormatProvider formatProvider)
        {
            return this.ToString(unitFormat, null, formatProvider);
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return this.ToString(UnitFormat.Default, format, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format, IFormatProvider formatProvider)
        {
            return QuantityHelper.ToString(
                this.Unit.FormatValue(this.value, format, formatProvider),
                UnitFormatHelper.GetNotation(this.Unit, unitFormat));
        }

        public Inductance CreateQuantity(double value, IUnit unit)
        {
            return new Inductance(value, unit);
        }

        IQuantity IDeferredQuantity.GetResult()
        {
            return this;
        }

        InductanceUnitSelector IQuantity<Inductance, InductanceUnitSelector>.CreateUnitSelector()
        {
            return new InductanceUnitSelector();
        }
    }
}