// --------------------------------------------------------------------------------------------------------------------
// <copyright file="LuminousIntensity.generated.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace Sundew.Quantities
{
    using global::Sundew.Quantities.Core;
    using global::Sundew.Quantities.Representations.Expressions;
    using global::Sundew.Quantities.UnitSelection;
    using global::Sundew.Quantities.UnitSelectors;
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Globalization;

    [GeneratedCode("Sundew.Quantities.Generator", "1.0.0.0")]
    public partial struct LuminousIntensity : IQuantity<LuminousIntensity, LuminousIntensityUnitSelector>
    {
        private readonly double value;

        public LuminousIntensity(double value, SelectUnit<LuminousIntensityUnitSelector> unitSelector)
            : this(value,  UnitBuilder.BuildUnit(unitSelector(new LuminousIntensityUnitSelector())))
        {
        }

        public LuminousIntensity(IQuantity quantity)
            : this(quantity.Value, quantity.Unit)
        {
        }

        public LuminousIntensity(double value)
            : this(value, units => units.BaseUnit)
        {
        }

        public LuminousIntensity(double value, IUnit unit)
        {
            this.value = value;
            this.Unit = unit;
        }

        double IQuantity.Value => this.value;

        public IUnit Unit { get; }

        public static LuminousIntensity operator +(LuminousIntensity quantity)
        {
            return quantity;
        }

        public static LuminousIntensity operator -(LuminousIntensity quantity)
        {
            return new LuminousIntensity(-quantity.value, quantity.Unit);
        }

        public static LuminousIntensity operator ++(LuminousIntensity quantity)
        {
            return new LuminousIntensity(quantity.value + 1, quantity.Unit);
        }

        public static LuminousIntensity operator --(LuminousIntensity quantity)
        {
            return new LuminousIntensity(quantity.value - 1, quantity.Unit);
        }

        public static LuminousIntensity operator +(LuminousIntensity lhs, double rhs)
        {
            return new LuminousIntensity(lhs.value + rhs, lhs.Unit);
        }

        public static LuminousIntensity operator -(LuminousIntensity lhs, double rhs)
        {
            return new LuminousIntensity(lhs.value - rhs, lhs.Unit);
        }

        public static LuminousIntensity operator *(LuminousIntensity lhs, double rhs)
        {
            return new LuminousIntensity(lhs.value * rhs, lhs.Unit);
        }

        public static LuminousIntensity operator /(LuminousIntensity lhs, double rhs)
        {
            return new LuminousIntensity(lhs.value / rhs, lhs.Unit);
        }

        public static LuminousIntensity operator +(LuminousIntensity lhs, LuminousIntensity rhs)
        {
            return new LuminousIntensity(QuantityOperations.Add(lhs, rhs));
        }

        public static LuminousIntensity operator -(LuminousIntensity lhs, LuminousIntensity rhs)
        {
            return new LuminousIntensity(QuantityOperations.Subtract(lhs, rhs));
        }

        public static double operator /(LuminousIntensity lhs, LuminousIntensity rhs)
        {
            return QuantityOperations.Divide(lhs, rhs).Value;
        }

        public static bool operator ==(LuminousIntensity lhs, LuminousIntensity rhs)
        {
            return QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator !=(LuminousIntensity lhs, LuminousIntensity rhs)
        {
            return !QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator >=(LuminousIntensity lhs, LuminousIntensity rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) >= 0;
        }

        public static bool operator <=(LuminousIntensity lhs, LuminousIntensity rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) <= 0;
        }

        public static bool operator >(LuminousIntensity lhs, LuminousIntensity rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) > 0;
        }

        public static bool operator <(LuminousIntensity lhs, LuminousIntensity rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) < 0;
        }

        public static Interval<LuminousIntensity> Interval(double min, double max, SelectUnit<LuminousIntensityUnitSelector> unitSelector)
        {
            return new Interval<LuminousIntensity>(min, max, unitSelector(new LuminousIntensityUnitSelector()));
        }

        public Squared<LuminousIntensity> Squared()
        {
            return new Squared<LuminousIntensity>(this);
        }

        public Cubed<LuminousIntensity> Cubed()
        {
            return new Cubed<LuminousIntensity>(this);
        }

        public double ToDouble(IUnit unit)
        {
            return QuantityOperations.ConvertToUnit(this, unit);
        }

        public IQuantity ToQuantity(IUnit unit)
        {
            return this.ToUnit(unit);
        }

        public LuminousIntensity ToUnit(IUnit unit)
        {
            return new LuminousIntensity(this.ToDouble(unit), unit);
        }

        public LuminousIntensity ToUnit(SelectUnit<LuminousIntensityUnitSelector> unitSelector)
        {
            return this.ToUnit(UnitBuilder.BuildUnit(unitSelector(new LuminousIntensityUnitSelector())));
        }

        public double ToDouble(SelectUnit<LuminousIntensityUnitSelector> unitSelector)
        {
            return this.ToDouble(UnitBuilder.BuildUnit(unitSelector(new LuminousIntensityUnitSelector())));
        }

        public override int GetHashCode()
        {
            return QuantityHelper.GetHashCode(this);
        }

        public override bool Equals(object obj)
        {
            return QuantityHelper.AreEqual(this, obj);
        }

        public bool Equals(IQuantity quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public bool Equals(LuminousIntensity quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public int CompareTo(object obj)
        {
            return QuantityHelper.CompareTo<LuminousIntensity>(this, obj);
        }

        public int CompareTo(IQuantity quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public int CompareTo(LuminousIntensity quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public override string ToString()
        {
            return this.ToString(CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat)
        {
            return this.ToString(unitFormat, null, CultureInfo.CurrentCulture);
        }

        public string ToString(string format)
        {
            return this.ToString(format, CultureInfo.CurrentCulture);
        }

        public string ToString(IFormatProvider formatProvider)
        {
            return this.ToString(null, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format)
        {
            return this.ToString(unitFormat, format, CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat, IFormatProvider formatProvider)
        {
            return this.ToString(unitFormat, null, formatProvider);
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return this.ToString(UnitFormat.Default, format, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format, IFormatProvider formatProvider)
        {
            return QuantityHelper.ToString(
                this.Unit.FormatValue(this.value, format, formatProvider),
                UnitFormatHelper.GetNotation(this.Unit, unitFormat));
        }

        public LuminousIntensity CreateQuantity(double value, IUnit unit)
        {
            return new LuminousIntensity(value, unit);
        }

        IQuantity IDeferredQuantity.GetResult()
        {
            return this;
        }

        LuminousIntensityUnitSelector IQuantity<LuminousIntensity, LuminousIntensityUnitSelector>.CreateUnitSelector()
        {
            return new LuminousIntensityUnitSelector();
        }
    }
}