// --------------------------------------------------------------------------------------------------------------------
// <copyright file="LuminousFlux.generated.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace Sundew.Quantities
{
    using global::Sundew.Quantities.Engine;
    using global::Sundew.Quantities.Engine.Quantities;
    using global::Sundew.Quantities.Engine.Representations.Hierarchical.Units;
    using global::Sundew.Quantities.Engine.UnitSelection;
    using global::Sundew.Quantities.UnitSelection;
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Globalization;

    [GeneratedCode("Sundew.Quantities.Generator", "1.0.0.0")]
    public partial struct LuminousFlux : IQuantity<LuminousFlux, LuminousFluxUnitSelector>
    {
        private readonly double value;

        public LuminousFlux(double value, SelectUnit<LuminousFluxUnitSelector> unitSelector)
            : this(value,  UnitBuilder.BuildUnit(unitSelector(new LuminousFluxUnitSelector())))
        {
        }

        public LuminousFlux(IQuantity quantity)
            : this(quantity.Value, quantity.Unit)
        {
        }

        public LuminousFlux(double value)
            : this(value, units => units.BaseUnit)
        {
        }

        public LuminousFlux(double value, IUnit unit)
        {
            this.value = value;
            this.Unit = unit;
        }

        double IQuantity.Value => this.value;

        public IUnit Unit { get; }

        public static LuminousFlux operator +(LuminousFlux quantity)
        {
            return quantity;
        }

        public static LuminousFlux operator -(LuminousFlux quantity)
        {
            return new LuminousFlux(-quantity.value, quantity.Unit);
        }

        public static LuminousFlux operator ++(LuminousFlux quantity)
        {
            return new LuminousFlux(quantity.value + 1, quantity.Unit);
        }

        public static LuminousFlux operator --(LuminousFlux quantity)
        {
            return new LuminousFlux(quantity.value - 1, quantity.Unit);
        }

        public static LuminousFlux operator +(LuminousFlux lhs, double rhs)
        {
            return new LuminousFlux(lhs.value + rhs, lhs.Unit);
        }

        public static LuminousFlux operator -(LuminousFlux lhs, double rhs)
        {
            return new LuminousFlux(lhs.value - rhs, lhs.Unit);
        }

        public static LuminousFlux operator *(LuminousFlux lhs, double rhs)
        {
            return new LuminousFlux(lhs.value * rhs, lhs.Unit);
        }

        public static LuminousFlux operator /(LuminousFlux lhs, double rhs)
        {
            return new LuminousFlux(lhs.value / rhs, lhs.Unit);
        }

        public static LuminousFlux operator +(LuminousFlux lhs, LuminousFlux rhs)
        {
            return new LuminousFlux(QuantityOperations.Add(lhs, rhs));
        }

        public static LuminousFlux operator -(LuminousFlux lhs, LuminousFlux rhs)
        {
            return new LuminousFlux(QuantityOperations.Subtract(lhs, rhs));
        }

        public static double operator /(LuminousFlux lhs, LuminousFlux rhs)
        {
            return QuantityOperations.Divide(lhs, rhs).Value;
        }

        public static bool operator ==(LuminousFlux lhs, LuminousFlux rhs)
        {
            return QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator !=(LuminousFlux lhs, LuminousFlux rhs)
        {
            return !QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator >=(LuminousFlux lhs, LuminousFlux rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) >= 0;
        }

        public static bool operator <=(LuminousFlux lhs, LuminousFlux rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) <= 0;
        }

        public static bool operator >(LuminousFlux lhs, LuminousFlux rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) > 0;
        }

        public static bool operator <(LuminousFlux lhs, LuminousFlux rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) < 0;
        }

        public static Interval<LuminousFlux> Interval(double min, double max, SelectUnit<LuminousFluxUnitSelector> unitSelector)
        {
            return new Interval<LuminousFlux>(min, max, unitSelector(new LuminousFluxUnitSelector()));
        }

        public Squared<LuminousFlux> Squared()
        {
            return new Squared<LuminousFlux>(this);
        }

        public Cubed<LuminousFlux> Cubed()
        {
            return new Cubed<LuminousFlux>(this);
        }

        public double ToDouble(IUnit unit)
        {
            return QuantityOperations.ConvertToUnit(this, unit);
        }

        public IQuantity ToQuantity(IUnit unit)
        {
            return this.ToUnit(unit);
        }

        public LuminousFlux ToUnit(IUnit unit)
        {
            return new LuminousFlux(this.ToDouble(unit), unit);
        }

        public LuminousFlux ToUnit(SelectUnit<LuminousFluxUnitSelector> unitSelector)
        {
            return this.ToUnit(UnitBuilder.BuildUnit(unitSelector(new LuminousFluxUnitSelector())));
        }

        public double ToDouble(SelectUnit<LuminousFluxUnitSelector> unitSelector)
        {
            return this.ToDouble(UnitBuilder.BuildUnit(unitSelector(new LuminousFluxUnitSelector())));
        }

        public override int GetHashCode()
        {
            return QuantityHelper.GetHashCode(this);
        }

        public override bool Equals(object obj)
        {
            return QuantityHelper.AreEqual(this, obj);
        }

        public bool Equals(IQuantity quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public bool Equals(LuminousFlux quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public int CompareTo(object obj)
        {
            return QuantityHelper.CompareTo<LuminousFlux>(this, obj);
        }

        public int CompareTo(IQuantity quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public int CompareTo(LuminousFlux quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public override string ToString()
        {
            return this.ToString(CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat)
        {
            return this.ToString(unitFormat, null, CultureInfo.CurrentCulture);
        }

        public string ToString(string format)
        {
            return this.ToString(format, CultureInfo.CurrentCulture);
        }

        public string ToString(IFormatProvider formatProvider)
        {
            return this.ToString(null, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format)
        {
            return this.ToString(unitFormat, format, CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat, IFormatProvider formatProvider)
        {
            return this.ToString(unitFormat, null, formatProvider);
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return this.ToString(UnitFormat.Default, format, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format, IFormatProvider formatProvider)
        {
            return QuantityHelper.ToString(
                this.Unit.FormatValue(this.value, format, formatProvider),
                UnitHelper.GetNotation(this.Unit, unitFormat));
        }

        public LuminousFlux CreateQuantity(double value, IUnit unit)
        {
            return new LuminousFlux(value, unit);
        }

        IQuantity IDeferredQuantity.GetResult()
        {
            return this;
        }

        LuminousFluxUnitSelector IQuantity<LuminousFlux, LuminousFluxUnitSelector>.CreateUnitSelector()
        {
            return new LuminousFluxUnitSelector();
        }
    }
}