// --------------------------------------------------------------------------------------------------------------------
// <copyright file="MagneticFluxDensity.generated.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace Sundew.Quantities
{
    using global::Sundew.Quantities.Core;
    using global::Sundew.Quantities.Representations.Expressions;
    using global::Sundew.Quantities.UnitSelection;
    using global::Sundew.Quantities.UnitSelectors;
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Globalization;

    [GeneratedCode("Sundew.Quantities.Generator", "1.0.0.0")]
    public partial struct MagneticFluxDensity : IQuantity<MagneticFluxDensity, MagneticFluxDensityUnitSelector>
    {
        private readonly double value;

        public MagneticFluxDensity(double value, SelectUnit<MagneticFluxDensityUnitSelector> unitSelector)
            : this(value,  UnitBuilder.BuildUnit(unitSelector(new MagneticFluxDensityUnitSelector())))
        {
        }

        public MagneticFluxDensity(IQuantity quantity)
            : this(quantity.Value, quantity.Unit)
        {
        }

        public MagneticFluxDensity(double value)
            : this(value, units => units.BaseUnit)
        {
        }

        public MagneticFluxDensity(double value, IUnit unit)
        {
            this.value = value;
            this.Unit = unit;
        }

        double IQuantity.Value => this.value;

        public IUnit Unit { get; }

        public static MagneticFluxDensity operator +(MagneticFluxDensity quantity)
        {
            return quantity;
        }

        public static MagneticFluxDensity operator -(MagneticFluxDensity quantity)
        {
            return new MagneticFluxDensity(-quantity.value, quantity.Unit);
        }

        public static MagneticFluxDensity operator ++(MagneticFluxDensity quantity)
        {
            return new MagneticFluxDensity(quantity.value + 1, quantity.Unit);
        }

        public static MagneticFluxDensity operator --(MagneticFluxDensity quantity)
        {
            return new MagneticFluxDensity(quantity.value - 1, quantity.Unit);
        }

        public static MagneticFluxDensity operator +(MagneticFluxDensity lhs, double rhs)
        {
            return new MagneticFluxDensity(lhs.value + rhs, lhs.Unit);
        }

        public static MagneticFluxDensity operator -(MagneticFluxDensity lhs, double rhs)
        {
            return new MagneticFluxDensity(lhs.value - rhs, lhs.Unit);
        }

        public static MagneticFluxDensity operator *(MagneticFluxDensity lhs, double rhs)
        {
            return new MagneticFluxDensity(lhs.value * rhs, lhs.Unit);
        }

        public static MagneticFluxDensity operator /(MagneticFluxDensity lhs, double rhs)
        {
            return new MagneticFluxDensity(lhs.value / rhs, lhs.Unit);
        }

        public static MagneticFluxDensity operator +(MagneticFluxDensity lhs, MagneticFluxDensity rhs)
        {
            return new MagneticFluxDensity(QuantityOperations.Add(lhs, rhs));
        }

        public static MagneticFluxDensity operator -(MagneticFluxDensity lhs, MagneticFluxDensity rhs)
        {
            return new MagneticFluxDensity(QuantityOperations.Subtract(lhs, rhs));
        }

        public static double operator /(MagneticFluxDensity lhs, MagneticFluxDensity rhs)
        {
            return QuantityOperations.Divide(lhs, rhs).Value;
        }

        public static bool operator ==(MagneticFluxDensity lhs, MagneticFluxDensity rhs)
        {
            return QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator !=(MagneticFluxDensity lhs, MagneticFluxDensity rhs)
        {
            return !QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator >=(MagneticFluxDensity lhs, MagneticFluxDensity rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) >= 0;
        }

        public static bool operator <=(MagneticFluxDensity lhs, MagneticFluxDensity rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) <= 0;
        }

        public static bool operator >(MagneticFluxDensity lhs, MagneticFluxDensity rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) > 0;
        }

        public static bool operator <(MagneticFluxDensity lhs, MagneticFluxDensity rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) < 0;
        }

        public static Interval<MagneticFluxDensity> Interval(double min, double max, SelectUnit<MagneticFluxDensityUnitSelector> unitSelector)
        {
            return new Interval<MagneticFluxDensity>(min, max, unitSelector(new MagneticFluxDensityUnitSelector()));
        }

        public Squared<MagneticFluxDensity> Squared()
        {
            return new Squared<MagneticFluxDensity>(this);
        }

        public Cubed<MagneticFluxDensity> Cubed()
        {
            return new Cubed<MagneticFluxDensity>(this);
        }

        public double ToDouble(IUnit unit)
        {
            return QuantityOperations.ConvertToUnit(this, unit);
        }

        public IQuantity ToQuantity(IUnit unit)
        {
            return this.ToUnit(unit);
        }

        public MagneticFluxDensity ToUnit(IUnit unit)
        {
            return new MagneticFluxDensity(this.ToDouble(unit), unit);
        }

        public MagneticFluxDensity ToUnit(SelectUnit<MagneticFluxDensityUnitSelector> unitSelector)
        {
            return this.ToUnit(UnitBuilder.BuildUnit(unitSelector(new MagneticFluxDensityUnitSelector())));
        }

        public double ToDouble(SelectUnit<MagneticFluxDensityUnitSelector> unitSelector)
        {
            return this.ToDouble(UnitBuilder.BuildUnit(unitSelector(new MagneticFluxDensityUnitSelector())));
        }

        public override int GetHashCode()
        {
            return QuantityHelper.GetHashCode(this);
        }

        public override bool Equals(object obj)
        {
            return QuantityHelper.AreEqual(this, obj);
        }

        public bool Equals(IQuantity quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public bool Equals(MagneticFluxDensity quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public int CompareTo(object obj)
        {
            return QuantityHelper.CompareTo<MagneticFluxDensity>(this, obj);
        }

        public int CompareTo(IQuantity quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public int CompareTo(MagneticFluxDensity quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public override string ToString()
        {
            return this.ToString(CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat)
        {
            return this.ToString(unitFormat, null, CultureInfo.CurrentCulture);
        }

        public string ToString(string format)
        {
            return this.ToString(format, CultureInfo.CurrentCulture);
        }

        public string ToString(IFormatProvider formatProvider)
        {
            return this.ToString(null, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format)
        {
            return this.ToString(unitFormat, format, CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat, IFormatProvider formatProvider)
        {
            return this.ToString(unitFormat, null, formatProvider);
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return this.ToString(UnitFormat.Default, format, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format, IFormatProvider formatProvider)
        {
            return QuantityHelper.ToString(
                this.Unit.FormatValue(this.value, format, formatProvider),
                UnitFormatHelper.GetNotation(this.Unit, unitFormat));
        }

        public MagneticFluxDensity CreateQuantity(double value, IUnit unit)
        {
            return new MagneticFluxDensity(value, unit);
        }

        IQuantity IDeferredQuantity.GetResult()
        {
            return this;
        }

        MagneticFluxDensityUnitSelector IQuantity<MagneticFluxDensity, MagneticFluxDensityUnitSelector>.CreateUnitSelector()
        {
            return new MagneticFluxDensityUnitSelector();
        }
    }
}