// --------------------------------------------------------------------------------------------------------------------
// <copyright file="MagneticFlux.generated.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace Sundew.Quantities
{
    using global::Sundew.Quantities.Engine;
    using global::Sundew.Quantities.Engine.Quantities;
    using global::Sundew.Quantities.Engine.Representations.Hierarchical.Units;
    using global::Sundew.Quantities.Engine.UnitSelection;
    using global::Sundew.Quantities.UnitSelection;
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Globalization;

    [GeneratedCode("Sundew.Quantities.Generator", "1.0.0.0")]
    public partial struct MagneticFlux : IQuantity<MagneticFlux, MagneticFluxUnitSelector>
    {
        private readonly double value;

        public MagneticFlux(double value, SelectUnit<MagneticFluxUnitSelector> unitSelector)
            : this(value,  UnitBuilder.BuildUnit(unitSelector(new MagneticFluxUnitSelector())))
        {
        }

        public MagneticFlux(IQuantity quantity)
            : this(quantity.Value, quantity.Unit)
        {
        }

        public MagneticFlux(double value)
            : this(value, units => units.BaseUnit)
        {
        }

        public MagneticFlux(double value, IUnit unit)
        {
            this.value = value;
            this.Unit = unit;
        }

        double IQuantity.Value => this.value;

        public IUnit Unit { get; }

        public static MagneticFlux operator +(MagneticFlux quantity)
        {
            return quantity;
        }

        public static MagneticFlux operator -(MagneticFlux quantity)
        {
            return new MagneticFlux(-quantity.value, quantity.Unit);
        }

        public static MagneticFlux operator ++(MagneticFlux quantity)
        {
            return new MagneticFlux(quantity.value + 1, quantity.Unit);
        }

        public static MagneticFlux operator --(MagneticFlux quantity)
        {
            return new MagneticFlux(quantity.value - 1, quantity.Unit);
        }

        public static MagneticFlux operator +(MagneticFlux lhs, double rhs)
        {
            return new MagneticFlux(lhs.value + rhs, lhs.Unit);
        }

        public static MagneticFlux operator -(MagneticFlux lhs, double rhs)
        {
            return new MagneticFlux(lhs.value - rhs, lhs.Unit);
        }

        public static MagneticFlux operator *(MagneticFlux lhs, double rhs)
        {
            return new MagneticFlux(lhs.value * rhs, lhs.Unit);
        }

        public static MagneticFlux operator /(MagneticFlux lhs, double rhs)
        {
            return new MagneticFlux(lhs.value / rhs, lhs.Unit);
        }

        public static MagneticFlux operator +(MagneticFlux lhs, MagneticFlux rhs)
        {
            return new MagneticFlux(QuantityOperations.Add(lhs, rhs));
        }

        public static MagneticFlux operator -(MagneticFlux lhs, MagneticFlux rhs)
        {
            return new MagneticFlux(QuantityOperations.Subtract(lhs, rhs));
        }

        public static double operator /(MagneticFlux lhs, MagneticFlux rhs)
        {
            return QuantityOperations.Divide(lhs, rhs).Value;
        }

        public static bool operator ==(MagneticFlux lhs, MagneticFlux rhs)
        {
            return QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator !=(MagneticFlux lhs, MagneticFlux rhs)
        {
            return !QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator >=(MagneticFlux lhs, MagneticFlux rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) >= 0;
        }

        public static bool operator <=(MagneticFlux lhs, MagneticFlux rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) <= 0;
        }

        public static bool operator >(MagneticFlux lhs, MagneticFlux rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) > 0;
        }

        public static bool operator <(MagneticFlux lhs, MagneticFlux rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) < 0;
        }

        public static Interval<MagneticFlux> Interval(double min, double max, SelectUnit<MagneticFluxUnitSelector> unitSelector)
        {
            return new Interval<MagneticFlux>(min, max, unitSelector(new MagneticFluxUnitSelector()));
        }

        public Squared<MagneticFlux> Squared()
        {
            return new Squared<MagneticFlux>(this);
        }

        public Cubed<MagneticFlux> Cubed()
        {
            return new Cubed<MagneticFlux>(this);
        }

        public double ToDouble(IUnit unit)
        {
            return QuantityOperations.ConvertToUnit(this, unit);
        }

        public IQuantity ToQuantity(IUnit unit)
        {
            return this.ToUnit(unit);
        }

        public MagneticFlux ToUnit(IUnit unit)
        {
            return new MagneticFlux(this.ToDouble(unit), unit);
        }

        public MagneticFlux ToUnit(SelectUnit<MagneticFluxUnitSelector> unitSelector)
        {
            return this.ToUnit(UnitBuilder.BuildUnit(unitSelector(new MagneticFluxUnitSelector())));
        }

        public double ToDouble(SelectUnit<MagneticFluxUnitSelector> unitSelector)
        {
            return this.ToDouble(UnitBuilder.BuildUnit(unitSelector(new MagneticFluxUnitSelector())));
        }

        public override int GetHashCode()
        {
            return QuantityHelper.GetHashCode(this);
        }

        public override bool Equals(object obj)
        {
            return QuantityHelper.AreEqual(this, obj);
        }

        public bool Equals(IQuantity quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public bool Equals(MagneticFlux quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public int CompareTo(object obj)
        {
            return QuantityHelper.CompareTo<MagneticFlux>(this, obj);
        }

        public int CompareTo(IQuantity quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public int CompareTo(MagneticFlux quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public override string ToString()
        {
            return this.ToString(CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat)
        {
            return this.ToString(unitFormat, null, CultureInfo.CurrentCulture);
        }

        public string ToString(string format)
        {
            return this.ToString(format, CultureInfo.CurrentCulture);
        }

        public string ToString(IFormatProvider formatProvider)
        {
            return this.ToString(null, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format)
        {
            return this.ToString(unitFormat, format, CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat, IFormatProvider formatProvider)
        {
            return this.ToString(unitFormat, null, formatProvider);
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return this.ToString(UnitFormat.Default, format, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format, IFormatProvider formatProvider)
        {
            return QuantityHelper.ToString(
                this.Unit.FormatValue(this.value, format, formatProvider),
                UnitHelper.GetNotation(this.Unit, unitFormat));
        }

        public MagneticFlux CreateQuantity(double value, IUnit unit)
        {
            return new MagneticFlux(value, unit);
        }

        IQuantity IDeferredQuantity.GetResult()
        {
            return this;
        }

        MagneticFluxUnitSelector IQuantity<MagneticFlux, MagneticFluxUnitSelector>.CreateUnitSelector()
        {
            return new MagneticFluxUnitSelector();
        }
    }
}