// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Mass.generated.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace Sundew.Quantities
{
    using global::Sundew.Quantities.Engine;
    using global::Sundew.Quantities.Engine.Quantities;
    using global::Sundew.Quantities.Engine.Representations.Hierarchical.Units;
    using global::Sundew.Quantities.Engine.UnitSelection;
    using global::Sundew.Quantities.UnitSelection;
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Globalization;

    [GeneratedCode("Sundew.Quantities.Generator", "1.0.0.0")]
    public partial struct Mass : IQuantity<Mass, MassUnitSelector>
    {
        private readonly double value;

        public Mass(double value, SelectUnit<MassUnitSelector> unitSelector)
            : this(value,  UnitBuilder.BuildUnit(unitSelector(new MassUnitSelector())))
        {
        }

        public Mass(IQuantity quantity)
            : this(quantity.Value, quantity.Unit)
        {
        }

        public Mass(double value)
            : this(value, units => units.BaseUnit)
        {
        }

        public Mass(double value, IUnit unit)
        {
            this.value = value;
            this.Unit = unit;
        }

        double IQuantity.Value => this.value;

        public IUnit Unit { get; }

        public static Mass operator +(Mass quantity)
        {
            return quantity;
        }

        public static Mass operator -(Mass quantity)
        {
            return new Mass(-quantity.value, quantity.Unit);
        }

        public static Mass operator ++(Mass quantity)
        {
            return new Mass(quantity.value + 1, quantity.Unit);
        }

        public static Mass operator --(Mass quantity)
        {
            return new Mass(quantity.value - 1, quantity.Unit);
        }

        public static Mass operator +(Mass lhs, double rhs)
        {
            return new Mass(lhs.value + rhs, lhs.Unit);
        }

        public static Mass operator -(Mass lhs, double rhs)
        {
            return new Mass(lhs.value - rhs, lhs.Unit);
        }

        public static Mass operator *(Mass lhs, double rhs)
        {
            return new Mass(lhs.value * rhs, lhs.Unit);
        }

        public static Mass operator /(Mass lhs, double rhs)
        {
            return new Mass(lhs.value / rhs, lhs.Unit);
        }

        public static Mass operator +(Mass lhs, Mass rhs)
        {
            return new Mass(QuantityOperations.Add(lhs, rhs));
        }

        public static Mass operator -(Mass lhs, Mass rhs)
        {
            return new Mass(QuantityOperations.Subtract(lhs, rhs));
        }

        public static double operator /(Mass lhs, Mass rhs)
        {
            return QuantityOperations.Divide(lhs, rhs).Value;
        }

        public static bool operator ==(Mass lhs, Mass rhs)
        {
            return QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator !=(Mass lhs, Mass rhs)
        {
            return !QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator >=(Mass lhs, Mass rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) >= 0;
        }

        public static bool operator <=(Mass lhs, Mass rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) <= 0;
        }

        public static bool operator >(Mass lhs, Mass rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) > 0;
        }

        public static bool operator <(Mass lhs, Mass rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) < 0;
        }

        public static Interval<Mass> Interval(double min, double max, SelectUnit<MassUnitSelector> unitSelector)
        {
            return new Interval<Mass>(min, max, unitSelector(new MassUnitSelector()));
        }

        public Squared<Mass> Squared()
        {
            return new Squared<Mass>(this);
        }

        public Cubed<Mass> Cubed()
        {
            return new Cubed<Mass>(this);
        }

        public double ToDouble(IUnit unit)
        {
            return QuantityOperations.ConvertToUnit(this, unit);
        }

        public IQuantity ToQuantity(IUnit unit)
        {
            return this.ToUnit(unit);
        }

        public Mass ToUnit(IUnit unit)
        {
            return new Mass(this.ToDouble(unit), unit);
        }

        public Mass ToUnit(SelectUnit<MassUnitSelector> unitSelector)
        {
            return this.ToUnit(UnitBuilder.BuildUnit(unitSelector(new MassUnitSelector())));
        }

        public double ToDouble(SelectUnit<MassUnitSelector> unitSelector)
        {
            return this.ToDouble(UnitBuilder.BuildUnit(unitSelector(new MassUnitSelector())));
        }

        public override int GetHashCode()
        {
            return QuantityHelper.GetHashCode(this);
        }

        public override bool Equals(object obj)
        {
            return QuantityHelper.AreEqual(this, obj);
        }

        public bool Equals(IQuantity quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public bool Equals(Mass quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public int CompareTo(object obj)
        {
            return QuantityHelper.CompareTo<Mass>(this, obj);
        }

        public int CompareTo(IQuantity quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public int CompareTo(Mass quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public override string ToString()
        {
            return this.ToString(CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat)
        {
            return this.ToString(unitFormat, null, CultureInfo.CurrentCulture);
        }

        public string ToString(string format)
        {
            return this.ToString(format, CultureInfo.CurrentCulture);
        }

        public string ToString(IFormatProvider formatProvider)
        {
            return this.ToString(null, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format)
        {
            return this.ToString(unitFormat, format, CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat, IFormatProvider formatProvider)
        {
            return this.ToString(unitFormat, null, formatProvider);
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return this.ToString(UnitFormat.Default, format, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format, IFormatProvider formatProvider)
        {
            return QuantityHelper.ToString(
                this.Unit.FormatValue(this.value, format, formatProvider),
                UnitHelper.GetNotation(this.Unit, unitFormat));
        }

        public Mass CreateQuantity(double value, IUnit unit)
        {
            return new Mass(value, unit);
        }

        IQuantity IDeferredQuantity.GetResult()
        {
            return this;
        }

        MassUnitSelector IQuantity<Mass, MassUnitSelector>.CreateUnitSelector()
        {
            return new MassUnitSelector();
        }
    }
}