// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Potential.generated.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace Sundew.Quantities
{
    using global::Sundew.Quantities.Core;
    using global::Sundew.Quantities.Representations.Expressions;
    using global::Sundew.Quantities.UnitSelection;
    using global::Sundew.Quantities.UnitSelectors;
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Globalization;

    [GeneratedCode("Sundew.Quantities.Generator", "1.0.0.0")]
    public partial struct Potential : IQuantity<Potential, PotentialUnitSelector>
    {
        private readonly double value;

        public Potential(double value, SelectUnit<PotentialUnitSelector> unitSelector)
            : this(value,  UnitBuilder.BuildUnit(unitSelector(new PotentialUnitSelector())))
        {
        }

        public Potential(IQuantity quantity)
            : this(quantity.Value, quantity.Unit)
        {
        }

        public Potential(double value)
            : this(value, units => units.BaseUnit)
        {
        }

        public Potential(double value, IUnit unit)
        {
            this.value = value;
            this.Unit = unit;
        }

        double IQuantity.Value => this.value;

        public IUnit Unit { get; }

        public static Potential operator +(Potential quantity)
        {
            return quantity;
        }

        public static Potential operator -(Potential quantity)
        {
            return new Potential(-quantity.value, quantity.Unit);
        }

        public static Potential operator ++(Potential quantity)
        {
            return new Potential(quantity.value + 1, quantity.Unit);
        }

        public static Potential operator --(Potential quantity)
        {
            return new Potential(quantity.value - 1, quantity.Unit);
        }

        public static Potential operator +(Potential lhs, double rhs)
        {
            return new Potential(lhs.value + rhs, lhs.Unit);
        }

        public static Potential operator -(Potential lhs, double rhs)
        {
            return new Potential(lhs.value - rhs, lhs.Unit);
        }

        public static Potential operator *(Potential lhs, double rhs)
        {
            return new Potential(lhs.value * rhs, lhs.Unit);
        }

        public static Potential operator /(Potential lhs, double rhs)
        {
            return new Potential(lhs.value / rhs, lhs.Unit);
        }

        public static Potential operator +(Potential lhs, Potential rhs)
        {
            return new Potential(QuantityOperations.Add(lhs, rhs));
        }

        public static Potential operator -(Potential lhs, Potential rhs)
        {
            return new Potential(QuantityOperations.Subtract(lhs, rhs));
        }

        public static double operator /(Potential lhs, Potential rhs)
        {
            return QuantityOperations.Divide(lhs, rhs).Value;
        }

        public static bool operator ==(Potential lhs, Potential rhs)
        {
            return QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator !=(Potential lhs, Potential rhs)
        {
            return !QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator >=(Potential lhs, Potential rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) >= 0;
        }

        public static bool operator <=(Potential lhs, Potential rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) <= 0;
        }

        public static bool operator >(Potential lhs, Potential rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) > 0;
        }

        public static bool operator <(Potential lhs, Potential rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) < 0;
        }

        public static Interval<Potential> Interval(double min, double max, SelectUnit<PotentialUnitSelector> unitSelector)
        {
            return new Interval<Potential>(min, max, unitSelector(new PotentialUnitSelector()));
        }

        public Squared<Potential> Squared()
        {
            return new Squared<Potential>(this);
        }

        public Cubed<Potential> Cubed()
        {
            return new Cubed<Potential>(this);
        }

        public double ToDouble(IUnit unit)
        {
            return QuantityOperations.ConvertToUnit(this, unit);
        }

        public IQuantity ToQuantity(IUnit unit)
        {
            return this.ToUnit(unit);
        }

        public Potential ToUnit(IUnit unit)
        {
            return new Potential(this.ToDouble(unit), unit);
        }

        public Potential ToUnit(SelectUnit<PotentialUnitSelector> unitSelector)
        {
            return this.ToUnit(UnitBuilder.BuildUnit(unitSelector(new PotentialUnitSelector())));
        }

        public double ToDouble(SelectUnit<PotentialUnitSelector> unitSelector)
        {
            return this.ToDouble(UnitBuilder.BuildUnit(unitSelector(new PotentialUnitSelector())));
        }

        public override int GetHashCode()
        {
            return QuantityHelper.GetHashCode(this);
        }

        public override bool Equals(object obj)
        {
            return QuantityHelper.AreEqual(this, obj);
        }

        public bool Equals(IQuantity quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public bool Equals(Potential quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public int CompareTo(object obj)
        {
            return QuantityHelper.CompareTo<Potential>(this, obj);
        }

        public int CompareTo(IQuantity quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public int CompareTo(Potential quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public override string ToString()
        {
            return this.ToString(CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat)
        {
            return this.ToString(unitFormat, null, CultureInfo.CurrentCulture);
        }

        public string ToString(string format)
        {
            return this.ToString(format, CultureInfo.CurrentCulture);
        }

        public string ToString(IFormatProvider formatProvider)
        {
            return this.ToString(null, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format)
        {
            return this.ToString(unitFormat, format, CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat, IFormatProvider formatProvider)
        {
            return this.ToString(unitFormat, null, formatProvider);
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return this.ToString(UnitFormat.Default, format, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format, IFormatProvider formatProvider)
        {
            return QuantityHelper.ToString(
                this.Unit.FormatValue(this.value, format, formatProvider),
                UnitFormatHelper.GetNotation(this.Unit, unitFormat));
        }

        public Potential CreateQuantity(double value, IUnit unit)
        {
            return new Potential(value, unit);
        }

        IQuantity IDeferredQuantity.GetResult()
        {
            return this;
        }

        PotentialUnitSelector IQuantity<Potential, PotentialUnitSelector>.CreateUnitSelector()
        {
            return new PotentialUnitSelector();
        }
    }
}