// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Resistance.generated.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace Sundew.Quantities
{
    using global::Sundew.Quantities.Engine;
    using global::Sundew.Quantities.Engine.Quantities;
    using global::Sundew.Quantities.Engine.Representations.Hierarchical.Units;
    using global::Sundew.Quantities.Engine.UnitSelection;
    using global::Sundew.Quantities.UnitSelection;
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Globalization;

    [GeneratedCode("Sundew.Quantities.Generator", "1.0.0.0")]
    public partial struct Resistance : IQuantity<Resistance, ResistanceUnitSelector>
    {
        private readonly double value;

        public Resistance(double value, SelectUnit<ResistanceUnitSelector> unitSelector)
            : this(value,  UnitBuilder.BuildUnit(unitSelector(new ResistanceUnitSelector())))
        {
        }

        public Resistance(IQuantity quantity)
            : this(quantity.Value, quantity.Unit)
        {
        }

        public Resistance(double value)
            : this(value, units => units.BaseUnit)
        {
        }

        public Resistance(double value, IUnit unit)
        {
            this.value = value;
            this.Unit = unit;
        }

        double IQuantity.Value => this.value;

        public IUnit Unit { get; }

        public static Resistance operator +(Resistance quantity)
        {
            return quantity;
        }

        public static Resistance operator -(Resistance quantity)
        {
            return new Resistance(-quantity.value, quantity.Unit);
        }

        public static Resistance operator ++(Resistance quantity)
        {
            return new Resistance(quantity.value + 1, quantity.Unit);
        }

        public static Resistance operator --(Resistance quantity)
        {
            return new Resistance(quantity.value - 1, quantity.Unit);
        }

        public static Resistance operator +(Resistance lhs, double rhs)
        {
            return new Resistance(lhs.value + rhs, lhs.Unit);
        }

        public static Resistance operator -(Resistance lhs, double rhs)
        {
            return new Resistance(lhs.value - rhs, lhs.Unit);
        }

        public static Resistance operator *(Resistance lhs, double rhs)
        {
            return new Resistance(lhs.value * rhs, lhs.Unit);
        }

        public static Resistance operator /(Resistance lhs, double rhs)
        {
            return new Resistance(lhs.value / rhs, lhs.Unit);
        }

        public static Resistance operator +(Resistance lhs, Resistance rhs)
        {
            return new Resistance(QuantityOperations.Add(lhs, rhs));
        }

        public static Resistance operator -(Resistance lhs, Resistance rhs)
        {
            return new Resistance(QuantityOperations.Subtract(lhs, rhs));
        }

        public static double operator /(Resistance lhs, Resistance rhs)
        {
            return QuantityOperations.Divide(lhs, rhs).Value;
        }

        public static bool operator ==(Resistance lhs, Resistance rhs)
        {
            return QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator !=(Resistance lhs, Resistance rhs)
        {
            return !QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator >=(Resistance lhs, Resistance rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) >= 0;
        }

        public static bool operator <=(Resistance lhs, Resistance rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) <= 0;
        }

        public static bool operator >(Resistance lhs, Resistance rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) > 0;
        }

        public static bool operator <(Resistance lhs, Resistance rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) < 0;
        }

        public static Interval<Resistance> Interval(double min, double max, SelectUnit<ResistanceUnitSelector> unitSelector)
        {
            return new Interval<Resistance>(min, max, unitSelector(new ResistanceUnitSelector()));
        }

        public Squared<Resistance> Squared()
        {
            return new Squared<Resistance>(this);
        }

        public Cubed<Resistance> Cubed()
        {
            return new Cubed<Resistance>(this);
        }

        public double ToDouble(IUnit unit)
        {
            return QuantityOperations.ConvertToUnit(this, unit);
        }

        public IQuantity ToQuantity(IUnit unit)
        {
            return this.ToUnit(unit);
        }

        public Resistance ToUnit(IUnit unit)
        {
            return new Resistance(this.ToDouble(unit), unit);
        }

        public Resistance ToUnit(SelectUnit<ResistanceUnitSelector> unitSelector)
        {
            return this.ToUnit(UnitBuilder.BuildUnit(unitSelector(new ResistanceUnitSelector())));
        }

        public double ToDouble(SelectUnit<ResistanceUnitSelector> unitSelector)
        {
            return this.ToDouble(UnitBuilder.BuildUnit(unitSelector(new ResistanceUnitSelector())));
        }

        public override int GetHashCode()
        {
            return QuantityHelper.GetHashCode(this);
        }

        public override bool Equals(object obj)
        {
            return QuantityHelper.AreEqual(this, obj);
        }

        public bool Equals(IQuantity quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public bool Equals(Resistance quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public int CompareTo(object obj)
        {
            return QuantityHelper.CompareTo<Resistance>(this, obj);
        }

        public int CompareTo(IQuantity quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public int CompareTo(Resistance quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public override string ToString()
        {
            return this.ToString(CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat)
        {
            return this.ToString(unitFormat, null, CultureInfo.CurrentCulture);
        }

        public string ToString(string format)
        {
            return this.ToString(format, CultureInfo.CurrentCulture);
        }

        public string ToString(IFormatProvider formatProvider)
        {
            return this.ToString(null, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format)
        {
            return this.ToString(unitFormat, format, CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat, IFormatProvider formatProvider)
        {
            return this.ToString(unitFormat, null, formatProvider);
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return this.ToString(UnitFormat.Default, format, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format, IFormatProvider formatProvider)
        {
            return QuantityHelper.ToString(
                this.Unit.FormatValue(this.value, format, formatProvider),
                UnitHelper.GetNotation(this.Unit, unitFormat));
        }

        public Resistance CreateQuantity(double value, IUnit unit)
        {
            return new Resistance(value, unit);
        }

        IQuantity IDeferredQuantity.GetResult()
        {
            return this;
        }

        ResistanceUnitSelector IQuantity<Resistance, ResistanceUnitSelector>.CreateUnitSelector()
        {
            return new ResistanceUnitSelector();
        }
    }
}