// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Temperature.generated.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace Sundew.Quantities
{
    using global::Sundew.Quantities.Core;
    using global::Sundew.Quantities.Representations.Expressions;
    using global::Sundew.Quantities.UnitSelection;
    using global::Sundew.Quantities.UnitSelectors;
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Globalization;

    [GeneratedCode("Sundew.Quantities.Generator", "1.0.0.0")]
    public partial struct Temperature : IQuantity<Temperature, TemperatureUnitSelector>
    {
        private readonly double value;

        public Temperature(double value, SelectUnit<TemperatureUnitSelector> unitSelector)
            : this(value,  UnitBuilder.BuildUnit(unitSelector(new TemperatureUnitSelector())))
        {
        }

        public Temperature(IQuantity quantity)
            : this(quantity.Value, quantity.Unit)
        {
        }

        public Temperature(double value)
            : this(value, units => units.BaseUnit)
        {
        }

        public Temperature(double value, IUnit unit)
        {
            this.value = value;
            this.Unit = unit;
        }

        double IQuantity.Value => this.value;

        public IUnit Unit { get; }

        public static Temperature operator +(Temperature quantity)
        {
            return quantity;
        }

        public static Temperature operator -(Temperature quantity)
        {
            return new Temperature(-quantity.value, quantity.Unit);
        }

        public static Temperature operator ++(Temperature quantity)
        {
            return new Temperature(quantity.value + 1, quantity.Unit);
        }

        public static Temperature operator --(Temperature quantity)
        {
            return new Temperature(quantity.value - 1, quantity.Unit);
        }

        public static Temperature operator +(Temperature lhs, double rhs)
        {
            return new Temperature(lhs.value + rhs, lhs.Unit);
        }

        public static Temperature operator -(Temperature lhs, double rhs)
        {
            return new Temperature(lhs.value - rhs, lhs.Unit);
        }

        public static Temperature operator *(Temperature lhs, double rhs)
        {
            return new Temperature(lhs.value * rhs, lhs.Unit);
        }

        public static Temperature operator /(Temperature lhs, double rhs)
        {
            return new Temperature(lhs.value / rhs, lhs.Unit);
        }

        public static Temperature operator +(Temperature lhs, Temperature rhs)
        {
            return new Temperature(QuantityOperations.Add(lhs, rhs));
        }

        public static Temperature operator -(Temperature lhs, Temperature rhs)
        {
            return new Temperature(QuantityOperations.Subtract(lhs, rhs));
        }

        public static double operator /(Temperature lhs, Temperature rhs)
        {
            return QuantityOperations.Divide(lhs, rhs).Value;
        }

        public static bool operator ==(Temperature lhs, Temperature rhs)
        {
            return QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator !=(Temperature lhs, Temperature rhs)
        {
            return !QuantityHelper.AreEqual(lhs, rhs);
        }

        public static bool operator >=(Temperature lhs, Temperature rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) >= 0;
        }

        public static bool operator <=(Temperature lhs, Temperature rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) <= 0;
        }

        public static bool operator >(Temperature lhs, Temperature rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) > 0;
        }

        public static bool operator <(Temperature lhs, Temperature rhs)
        {
            return QuantityHelper.CompareTo(lhs, rhs) < 0;
        }

        public static Interval<Temperature> Interval(double min, double max, SelectUnit<TemperatureUnitSelector> unitSelector)
        {
            return new Interval<Temperature>(min, max, unitSelector(new TemperatureUnitSelector()));
        }

        public Squared<Temperature> Squared()
        {
            return new Squared<Temperature>(this);
        }

        public Cubed<Temperature> Cubed()
        {
            return new Cubed<Temperature>(this);
        }

        public double ToDouble(IUnit unit)
        {
            return QuantityOperations.ConvertToUnit(this, unit);
        }

        public IQuantity ToQuantity(IUnit unit)
        {
            return this.ToUnit(unit);
        }

        public Temperature ToUnit(IUnit unit)
        {
            return new Temperature(this.ToDouble(unit), unit);
        }

        public Temperature ToUnit(SelectUnit<TemperatureUnitSelector> unitSelector)
        {
            return this.ToUnit(UnitBuilder.BuildUnit(unitSelector(new TemperatureUnitSelector())));
        }

        public double ToDouble(SelectUnit<TemperatureUnitSelector> unitSelector)
        {
            return this.ToDouble(UnitBuilder.BuildUnit(unitSelector(new TemperatureUnitSelector())));
        }

        public override int GetHashCode()
        {
            return QuantityHelper.GetHashCode(this);
        }

        public override bool Equals(object obj)
        {
            return QuantityHelper.AreEqual(this, obj);
        }

        public bool Equals(IQuantity quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public bool Equals(Temperature quantity)
        {
            return QuantityHelper.AreEqual(this, quantity);
        }

        public int CompareTo(object obj)
        {
            return QuantityHelper.CompareTo<Temperature>(this, obj);
        }

        public int CompareTo(IQuantity quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public int CompareTo(Temperature quantity)
        {
            return QuantityHelper.CompareTo(this, quantity);
        }

        public override string ToString()
        {
            return this.ToString(CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat)
        {
            return this.ToString(unitFormat, null, CultureInfo.CurrentCulture);
        }

        public string ToString(string format)
        {
            return this.ToString(format, CultureInfo.CurrentCulture);
        }

        public string ToString(IFormatProvider formatProvider)
        {
            return this.ToString(null, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format)
        {
            return this.ToString(unitFormat, format, CultureInfo.CurrentCulture);
        }

        public string ToString(UnitFormat unitFormat, IFormatProvider formatProvider)
        {
            return this.ToString(unitFormat, null, formatProvider);
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return this.ToString(UnitFormat.Default, format, formatProvider);
        }

        public string ToString(UnitFormat unitFormat, string format, IFormatProvider formatProvider)
        {
            return QuantityHelper.ToString(
                this.Unit.FormatValue(this.value, format, formatProvider),
                UnitFormatHelper.GetNotation(this.Unit, unitFormat));
        }

        public Temperature CreateQuantity(double value, IUnit unit)
        {
            return new Temperature(value, unit);
        }

        IQuantity IDeferredQuantity.GetResult()
        {
            return this;
        }

        TemperatureUnitSelector IQuantity<Temperature, TemperatureUnitSelector>.CreateUnitSelector()
        {
            return new TemperatureUnitSelector();
        }
    }
}