
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IAreaUnitSelector.generated.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace Sundew.Quantities.UnitSelectors
{
    using global::System.CodeDom.Compiler;
    using global::Sundew.Quantities.Representations.Expressions;
    using global::Sundew.Quantities.Representations.Units;
    using global::Sundew.Quantities.UnitSelection;

    /// <summary>
    /// Interface for <see cref="Area"/> unit selector.
    /// </summary>
    [GeneratedCode("Sundew.Quantities.Generator.UnitSelectors.UnitSelectorInterfaceGenerator", "1.0.0.0")]
    public interface IAreaUnitSelector : IUnitSelector
    {
        /// <summary>
        /// Gets the meter.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Meters { get; }

        /// <summary>
        /// Gets the mile.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Miles { get; }

        /// <summary>
        /// Gets the feet.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Feet { get; }

        /// <summary>
        /// Gets the inches.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Inches { get; }

        /// <summary>
        /// Gets the nautical miles.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression NauticalMiles { get; }

        /// <summary>
        /// Gets the yard.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Yards { get; }
    }
}
