
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IFrequencyUnitSelector.generated.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace Sundew.Quantities.UnitSelectors
{
    using global::System.CodeDom.Compiler;
    using global::Sundew.Quantities.Representations.Expressions;
    using global::Sundew.Quantities.Representations.Units;
    using global::Sundew.Quantities.UnitSelection;

    /// <summary>
    /// Interface for <see cref="Frequency"/> unit selector.
    /// </summary>
    [GeneratedCode("Sundew.Quantities.Generator.UnitSelectors.UnitSelectorInterfaceGenerator", "1.0.0.0")]
    public interface IFrequencyUnitSelector : IUnitSelector
    {
        /// <summary>
        /// Gets the hertz.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Hertz { get; }

        /// <summary>
        /// Gets the second.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Seconds { get; }

        /// <summary>
        /// Gets the year.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Years { get; }

        /// <summary>
        /// Gets the month.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Months { get; }

        /// <summary>
        /// Gets the week.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Weeks { get; }

        /// <summary>
        /// Gets the day.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Days { get; }

        /// <summary>
        /// Gets the minute.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Minutes { get; }

        /// <summary>
        /// Gets the hour.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Hours { get; }
    }
}
