
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IMassUnitSelector.generated.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace Sundew.Quantities.UnitSelectors
{
    using global::Sundew.Quantities.Representations.Expressions;
    using global::Sundew.Quantities.Representations.Units;
    using global::Sundew.Quantities.UnitSelection;
    using global::System.CodeDom.Compiler;

    /// <summary>
    /// Interface for <see cref="Mass"/> unit selector.
    /// </summary>
    [GeneratedCode("Sundew.Quantities.Generator.UnitSelectors.UnitSelectorInterfaceGenerator", "1.0.0.0")]
    public interface IMassUnitSelector : IUnitSelector
    {
        /// <summary>
        /// Gets the kilo gram.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression KiloGrams { get; }

        /// <summary>
        /// Gets the gram.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Grams { get; }

        /// <summary>
        /// Gets the tonne.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Tonnes { get; }

        /// <summary>
        /// Gets the chinese metric ounce.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression ChineseMetricOunces { get; }

        /// <summary>
        /// Gets the dutch metric ounce.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression DutchMetricOunces { get; }

        /// <summary>
        /// Gets the international avoirdupois ounce.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression InternationalAvoirdupoisOunces { get; }

        /// <summary>
        /// Gets the international troy ounce.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression InternationalTroyOunces { get; }

        /// <summary>
        /// Gets the maria theresa ounce.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression MariaTheresaOunces { get; }

        /// <summary>
        /// Gets the ounce.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression Ounces { get; }

        /// <summary>
        /// Gets the spanish ounce.
        /// </summary>
        /// <value>
        /// The yard <see cref="Expression"/>.
        /// </value>
        Expression SpanishOunces { get; }
    }
}
