
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IPrefixedAreaUnitSelector.generated.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace Sundew.Quantities.UnitSelectors
{
    using global::System.CodeDom.Compiler;
    using global::Sundew.Quantities.UnitSelection;

    /// <summary>
    /// Interface for <see cref="Area"/> unit selector.
    /// </summary>
    [GeneratedCode("Sundew.Quantities.Generator.UnitSelectors.PrefixedUnitSelectorInterfaceGenerator", "1.0.0.0")]
    public interface IPrefixedAreaUnitSelector : IPrefixSelector<IAreaUnitSelector>, IAreaUnitSelector 
    {
    }
}
