// --------------------------------------------------------------------------------------------------------------------
// <copyright file="PrefixedUnitSelectorInterfaceGenerator.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace Sundew.Quantities.Generator.UnitSelectors
{
    using Sundew.Code.Generation.CSharp;
    using System.Collections.Generic;
    using Sundew.Text.Generation.Common;
    using Sundew.Text.Generation;

    public class PrefixedUnitSelectorInterfaceGenerator : IGenerator<CodeSetup, CodeGeneratorSetup, QuantityModel>
    {
        public IReadOnlyList<Run> Prepare(CodeSetup codeSetup, CodeGeneratorSetup codeGeneratorSetup, QuantityModel model, string modelPath)
        {
            return new[]
            {
                new Run(NameGenerator.GetFolderPath(codeSetup, codeGeneratorSetup),
                    NameGenerator.GetFileName($"IPrefixed{model.Name}UnitSelector", codeSetup, codeGeneratorSetup))
            };
        }

        public string Generate(CodeSetup codeSetup, CodeGeneratorSetup codeGeneratorSetup, QuantityModel model, OutputInfo outputInfo)
        {
            return $@"
// --------------------------------------------------------------------------------------------------------------------
// <copyright file=""{outputInfo.FileName}"" company=""Hukano"">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace {NamespaceGenerator.GetNamespace(outputInfo.TargetInfo.FilePath, outputInfo.FolderPath)}
{{
{UsingsGenerator.GetUsings(codeSetup.UseGlobalUsings | codeGeneratorSetup.UseGlobalUsings, 4, codeSetup.Usings, codeGeneratorSetup.Usings)}

    /// <summary>
    /// Interface for <see cref=""{model.Name}""/> unit selector.
    /// </summary>
    [GeneratedCode(""{this.GetType().FullName}"", ""{this.GetType().Assembly.GetName().Version}"")]
    public interface IPrefixed{model.Name}UnitSelector : IPrefixSelector<I{model.Name}UnitSelector>, I{model.Name}UnitSelector 
    {{
    }}
}}
";
        }
    }
}