// --------------------------------------------------------------------------------------------------------------------
// <copyright file="UnitSelectorInterfaceGenerator.cs" company="Hukano">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace Sundew.Quantities.Generator.UnitSelectors
{
    using Sundew.Code.Generation.CSharp;
    using System.Collections.Generic;
    using System.Text;
    using Sundew.Text.Generation;
    using Sundew.Text.Generation.Common;

    public class UnitSelectorInterfaceGenerator : IGenerator<CodeSetup, CodeGeneratorSetup, QuantityModel>
    {
        public IReadOnlyList<Run> Prepare(CodeSetup codeSetup, CodeGeneratorSetup codeGeneratorSetup, QuantityModel model, string modelPath)
        {
            return new[]
            {
                new Run(NameGenerator.GetFolderPath(codeSetup, codeGeneratorSetup),
                    NameGenerator.GetFileName($"I{model.Name}UnitSelector", codeSetup, codeGeneratorSetup))
            };
        }

        public string Generate(CodeSetup codeSetup, CodeGeneratorSetup codeGeneratorSetup, QuantityModel model, OutputInfo outputInfo)
        {
            return $@"
// --------------------------------------------------------------------------------------------------------------------
// <copyright file=""{outputInfo.FileName}"" company=""Hukano"">
// Copyright (c) Hukano. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// <auto-generated />
namespace {NamespaceGenerator.GetNamespace(outputInfo.TargetInfo.FilePath, outputInfo.FolderPath)}
{{
{UsingsGenerator.GetUsings(codeSetup.UseGlobalUsings | codeGeneratorSetup.UseGlobalUsings, 4, codeSetup.Usings, codeGeneratorSetup.Usings)}

    /// <summary>
    /// Interface for <see cref=""{model.Name}""/> unit selector.
    /// </summary>
    [GeneratedCode(""{this.GetType().FullName}"", ""{this.GetType().Assembly.GetName().Version}"")]
    public interface I{model.Name}UnitSelector : IUnitSelector
    {{
{this.GetUnits(model)}
    }}
}}
";
        }

        private IndentedString GetUnits(QuantityModel model)
        {
            var stringBuilder = new StringBuilder();
            foreach (var unitModel in model.Units)
            {
                stringBuilder.AppendLine($@"
/// <summary>
/// Gets the {UnitsGenerator.GetDocumentationName(unitModel)}.
/// </summary>
/// <value>
/// The yard <see cref=""Expression""/>.
/// </value>
Expression {unitModel.Identifier} {{ get; }}");
            }

            return new IndentedString(8, stringBuilder.ToString());
        }
    }
}